"""List of cask packages to install."""

casks = [
#'cloudmounter',
'cyberduck',
#'duet',
'grammarly',
'handbrake',
'iina',
'appcleaner',
'google-chrome',
'simple-comic',
'transmission',
'lastpass',
'tunnelbear',
#'fliqlo',
'megasync',
'the-unarchiver',
# 'vnc-viewer',
#'coconutbattery',
'vnc-server',
'applepi-baker',
'sdformatter',
'boom',
#'calibre',
'spotify',
#'spotifree',
'onedrive',
'virtualbox-extension-pack',
#'geektool',
'visual-studio-code',
'google-backup-and-sync',
'omnidisksweeper',
'virtualbox',
#'rsyncosx',
]